# Generated by Django 5.1 on 2024-08-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='section',
            field=models.CharField(choices=[('section1', 'Section 1'), ('section2', 'Section 2')], default='Section1', max_length=20),
            preserve_default=False,
        ),
    ]